[package]
name = "polymod"
version = "0.0.0"
edition = "2021"

[dependencies]
catppuccin-egui = "5.2.0"
index_vec = "0.1.3"
indexmap = "2.2.6"
itertools = "0.12.1"
ordered-float = "4.2.0"
three-d = { version = "0.17.0", features = ["egui-gui"] }
